workflows:
  react-native-android:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install expo@~50.0.0
      - name: Build Android
        script: |
          # Эти переменные заменяют старый флаг --no-interactive
          export EXPO_NO_TELEMETRY=1
          export CI=1
          
          # Очистка и создание папки android
          rm -rf android
          npx expo prebuild --platform android --skip-dependency-install
          
          # Сама сборка APK
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
